// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "ui.h"
#include "ui_helpers.h"

#if !defined(APOLLO510DL_LITE) || defined(APOLLO510DL_LITE_BLOOD_OXY)
#define UI_HAS_BLOOD_OXY 1
#endif

#if !defined(APOLLO510DL_LITE) || defined(APOLLO510DL_LITE_WEATHER)
#define UI_HAS_WEATHER 1
#endif

#if !defined(APOLLO510DL_LITE) || defined(APOLLO510DL_LITE_CALL)
#define UI_HAS_CALL 1
#endif

///////////////////// VARIABLES ////////////////////
// void sec_Animation( lv_obj_t *TargetObject, int delay);
// void min_Animation( lv_obj_t *TargetObject, int delay);
// void hour_Animation( lv_obj_t *TargetObject, int delay);
// void left_Animation( lv_obj_t *TargetObject, int delay);
// void right_Animation( lv_obj_t *TargetObject, int delay);
// void opa_on_Animation( lv_obj_t *TargetObject, int delay);
// void dots_Animation( lv_obj_t *TargetObject, int delay);
// void top_Animation( lv_obj_t *TargetObject, int delay);
// void cloud_Animation( lv_obj_t *TargetObject, int delay);
// void blood2_Animation( lv_obj_t *TargetObject, int delay);
// void blood1_Animation( lv_obj_t *TargetObject, int delay);
// void heart_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_watch_digital
//void ui_watch_digital_screen_init(void);
//void ui_event_watch_digital( lv_event_t * e);
lv_obj_t *ui_watch_digital;
lv_obj_t *ui_watch_digital_bg_1;
lv_obj_t *ui_watch_digital_hour_group;
lv_obj_t *ui_watch_digital_label_hour_1;
lv_obj_t *ui_watch_digital_label_hour_2;
lv_obj_t *ui_watch_digital_label_min;
lv_obj_t *ui_watch_digital_battery_group;
lv_obj_t *ui_watch_digital_date_group;
lv_obj_t *ui_watch_digital_weather_group_1;
lv_obj_t *ui_watch_digital_weather_title_group_1;
lv_obj_t *ui_watch_digital_step_group;
lv_obj_t *ui_watch_digital_daily_mission_group;
//void ui_event_watch_digital_button_top_buttontop( lv_event_t * e);
lv_obj_t *ui_watch_digital_button_top;
//void ui_event_watch_digital_button_down_buttondown( lv_event_t * e);
lv_obj_t *ui_watch_digital_button_down;
lv_obj_t *ui_watch_digital_sec_dot;
lv_obj_t *ui_watch_digital_weather_dots_group2;
lv_obj_t *ui_watch_digital_dot14;
lv_obj_t *ui_watch_digital_dot15;
// CUSTOM VARIABLES

// SCREEN: ui_watch_analog
//void ui_watch_analog_screen_init(void);
//void ui_event_watch_analog( lv_event_t * e);
lv_obj_t *ui_watch_analog;
lv_obj_t *ui_watch_analog_bg_2;
lv_obj_t *ui_watch_analog_clock;
lv_obj_t *ui_watch_analog_dots;
lv_obj_t *ui_watch_analog_battery_group1;
lv_obj_t *ui_watch_analog_date_group2;
lv_obj_t *ui_watch_analog_day2;
lv_obj_t *ui_watch_analog_month2;
lv_obj_t *ui_watch_analog_year2;
lv_obj_t *ui_watch_analog_weather_title_group_2;
lv_obj_t *ui_watch_analog_weather_group_5;
lv_obj_t *ui_watch_analog_degree_7;
lv_obj_t *ui_watch_analog_cloud_fog_3;
lv_obj_t *ui_watch_analog_step_group2;
lv_obj_t *ui_watch_analog_daily_mission_group1;
//void ui_event_watch_analog_button_top1_buttontop( lv_event_t * e);
lv_obj_t *ui_watch_analog_button_top1;
//void ui_event_watch_analog_button_down1_buttondown( lv_event_t * e);
lv_obj_t *ui_watch_analog_button_down1;
lv_obj_t *ui_watch_analog_clock_group;
lv_obj_t *ui_watch_analog_sec;
lv_obj_t *ui_watch_analog_min;
lv_obj_t *ui_watch_analog_hour;
lv_obj_t *ui_watch_analog_dots_group;
lv_obj_t *ui_watch_analog_dot16;
lv_obj_t *ui_watch_analog_dot17;
// CUSTOM VARIABLES

// SCREEN: ui_call
//void ui_call_screen_init(void);
//void ui_event_call( lv_event_t * e);
lv_obj_t *ui_call;
lv_obj_t *ui_call_bg_3;
lv_obj_t *ui_call_avatar;
lv_obj_t *ui_call_avatar_label;
lv_obj_t *ui_call_call_time;
lv_obj_t *ui_call_mute;
//void ui_event_call_button_down2_buttondown( lv_event_t * e);
lv_obj_t *ui_call_button_down2;
lv_obj_t *ui_call_volume_group;
lv_obj_t *ui_call_volume_percent;
lv_obj_t *ui_call_volume_image;
//void ui_event_call_volume_arc( lv_event_t * e);
lv_obj_t *ui_call_volume_arc;
//void ui_event_call_button_top2_buttontop( lv_event_t * e);
lv_obj_t *ui_call_button_top2;
// CUSTOM VARIABLES

// SCREEN: ui_weather_1
//void ui_weather_1_screen_init(void);
//void ui_event_weather_1( lv_event_t * e);
lv_obj_t *ui_weather_1;
lv_obj_t *ui_weather_1_bg_4;
lv_obj_t *ui_weather_1_city_gruop_1;
lv_obj_t *ui_weather_1_weather_title_group_3;
lv_obj_t *ui_weather_1_label_degree;
lv_obj_t *ui_weather_1_rain_group;
lv_obj_t *ui_weather_1_rain_icon;
lv_obj_t *ui_weather_1_rain_percent;
lv_obj_t *ui_weather_1_wind_group;
lv_obj_t *ui_weather_1_wind_icon;
lv_obj_t *ui_weather_1_wind_speed;
lv_obj_t *ui_weather_1_weather_dots_group;
lv_obj_t *ui_weather_1_dot1;
lv_obj_t *ui_weather_1_dot2;
lv_obj_t *ui_weather_1_weather_image_group;
lv_obj_t *ui_weather_1_sun;
lv_obj_t *ui_weather_1_clouds;
//void ui_event_weather_1_button_down3_buttondown( lv_event_t * e);
lv_obj_t *ui_weather_1_button_down3;
// CUSTOM VARIABLES

// SCREEN: ui_weather_2
//void ui_weather_2_screen_init(void);
//void ui_event_weather_2( lv_event_t * e);
lv_obj_t *ui_weather_2;
lv_obj_t *ui_weather_2_bg5;
lv_obj_t *ui_weather_2_weather_dots_group1;
lv_obj_t *ui_weather_2_dot3;
lv_obj_t *ui_weather_2_dot4;
lv_obj_t *ui_weather_2_content;
lv_obj_t *ui_weather_2_city_gruop_2;
lv_obj_t *ui_weather_2_todady_weather_content;
lv_obj_t *ui_weather_2_today_weather_group;
lv_obj_t *ui_weather_2_today_weather_group1;
lv_obj_t *ui_weather_2_today_weather_group2;
lv_obj_t *ui_weather_2_today_weather_group3;
lv_obj_t *ui_weather_2_today_weather_group4;
lv_obj_t *ui_weather_2_today_weather_group5;
lv_obj_t *ui_weather_2_today_weather_group6;
lv_obj_t *ui_weather_2_today_weather_group7;
lv_obj_t *ui_weather_2_today_weather_group8;
lv_obj_t *ui_weather_2_days_forecast;
lv_obj_t *ui_weather_2_week_weather_group;
lv_obj_t *ui_weather_2_forecast_group;
lv_obj_t *ui_weather_2_forecast_group1;
lv_obj_t *ui_weather_2_forecast_group2;
lv_obj_t *ui_weather_2_forecast_group3;
lv_obj_t *ui_weather_2_forecast_group4;
lv_obj_t *ui_weather_2_forecast_group5;
lv_obj_t *ui_weather_2_space;
//void ui_event_weather_2_button_down4_buttondown( lv_event_t * e);
lv_obj_t *ui_weather_2_button_down4;
// CUSTOM VARIABLES

// SCREEN: ui_blood_oxy
//void ui_blood_oxy_screen_init(void);
//void ui_event_blood_oxy( lv_event_t * e);
lv_obj_t *ui_blood_oxy;
lv_obj_t *ui_blood_oxy_bg6;
lv_obj_t *ui_blood_oxy_title_group_1;
//void ui_event_blood_oxy_button_down5_buttondown( lv_event_t * e);
lv_obj_t *ui_blood_oxy_button_down5;
//void ui_event_blood_oxy_button_round_buttonround( lv_event_t * e);
lv_obj_t *ui_blood_oxy_button_round;
lv_obj_t *ui_blood_oxy_blood_presure_group;
lv_obj_t *ui_blood_oxy_blood_oxygen;
lv_obj_t *ui_blood_oxy_percent;
lv_obj_t *ui_blood_oxy_pulse_group;
lv_obj_t *ui_blood_oxy_arc_spo2;
lv_obj_t *ui_blood_oxy_precent_70;
lv_obj_t *ui_blood_oxy_precent_100;
lv_obj_t *ui_blood_oxy_health_dots_group;
lv_obj_t *ui_blood_oxy_dot7;
lv_obj_t *ui_blood_oxy_dot6;
lv_obj_t *ui_blood_oxy_dot5;
lv_obj_t *ui_blood_oxy_dots_group1;
lv_obj_t *ui_blood_oxy_dot18;
lv_obj_t *ui_blood_oxy_dot19;
// CUSTOM VARIABLES

// SCREEN: ui_ecg
//void ui_ecg_screen_init(void);
//void ui_event_ecg( lv_event_t * e);
lv_obj_t *ui_ecg;
lv_obj_t *ui_ecg_Image1;
lv_obj_t *ui_ecg_bg1;
lv_obj_t *ui_ecg_title_group_2;
//void ui_event_ecg_button_down6_buttondown( lv_event_t * e);
lv_obj_t *ui_ecg_button_down6;
//void ui_event_ecg_button_round1_buttonround( lv_event_t * e);
lv_obj_t *ui_ecg_button_round1;
lv_obj_t *ui_ecg_pulse_group1;
lv_obj_t *ui_ecg_health_dots_group1;
lv_obj_t *ui_ecg_dot9;
lv_obj_t *ui_ecg_dot8;
lv_obj_t *ui_ecg_dot10;
lv_obj_t *ui_ecg_chart_group;
lv_obj_t *ui_ecg_chart_ecg;
lv_obj_t *ui_ecg_chart_ecg_Xaxis;
lv_obj_t *ui_ecg_chart_ecg_Yaxis1;
lv_obj_t *ui_ecg_chart_ecg_Yaxis2;
// CUSTOM VARIABLES

// SCREEN: ui_blood_pressure
//void ui_blood_pressure_screen_init(void);
//void ui_event_blood_pressure( lv_event_t * e);
lv_obj_t *ui_blood_pressure;
lv_obj_t *ui_blood_pressure_bg2;
lv_obj_t *ui_blood_pressure_Image3;
lv_obj_t *ui_blood_pressure_title_group_3;
//void ui_event_blood_pressure_button_down7_buttondown( lv_event_t * e);
lv_obj_t *ui_blood_pressure_button_down7;
//void ui_event_blood_pressure_button_round2_buttonround( lv_event_t * e);
lv_obj_t *ui_blood_pressure_button_round2;
lv_obj_t *ui_blood_pressure_blood_presure_group1;
lv_obj_t *ui_blood_pressure_sys_group;
lv_obj_t *ui_blood_pressure_sys;
lv_obj_t *ui_blood_pressure_mmhg1;
lv_obj_t *ui_blood_pressure_blood_oxygen1;
lv_obj_t *ui_blood_pressure_pulse_group2;
lv_obj_t *ui_blood_pressure_blood_presure_group2;
lv_obj_t *ui_blood_pressure_dia_group;
lv_obj_t *ui_blood_pressure_dia;
lv_obj_t *ui_blood_pressure_mmhg2;
lv_obj_t *ui_blood_pressure_blood_oxygen2;
lv_obj_t *ui_blood_pressure_health_dots_group2;
lv_obj_t *ui_blood_pressure_dot12;
lv_obj_t *ui_blood_pressure_dot13;
lv_obj_t *ui_blood_pressure_dot11;
// CUSTOM VARIABLES

// SCREEN: ui_measuing
//void ui_measuing_screen_init(void);
//void ui_event_measuing( lv_event_t * e);
lv_obj_t *ui_measuing;
lv_obj_t *ui_measuing_bg7;
lv_obj_t *ui_measuing_pulse_group3;
lv_obj_t *ui_measuing_measuring;
lv_obj_t *ui_measuing_Spinner2;
lv_obj_t *ui_measuing_blood_group;
lv_obj_t *ui_measuing_blood1;
lv_obj_t *ui_measuing_blood_fill;
lv_obj_t *ui_measuing_blood2;
//void ui_event_measuing_x_button( lv_event_t * e);
lv_obj_t *ui_measuing_x_button;
lv_obj_t *ui_measuing_x;
// CUSTOM VARIABLES

// EVENTS
//void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void sec_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 60000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 3600 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}
void min_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 1400 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}
void hour_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle );
lv_anim_set_values(&PropertyAnimation_0, 0, 300 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle );
lv_anim_start(&PropertyAnimation_0);

}
void left_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -100, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void right_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 150, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 300);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_1, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, true );
lv_anim_start(&PropertyAnimation_1);

}
void opa_on_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);

}
void dots_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 250);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 0, 255 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 250);
lv_anim_set_playback_delay(&PropertyAnimation_0, 250);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 500);
lv_anim_set_early_apply( &PropertyAnimation_0, true );
lv_anim_start(&PropertyAnimation_0);

}
void top_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, -100, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}
void cloud_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y );
lv_anim_set_values(&PropertyAnimation_0, 0, 10 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 1000);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y );
lv_anim_start(&PropertyAnimation_0);

}
void blood2_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 3000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 166 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void blood1_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 2000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 166, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void heart_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 900);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, 120, 60 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}

#ifdef APOLLO510DL_LITE
#define UI_SWIPE_MIN_PX  35

typedef enum {
    UI_SWIPE_NONE = 0,
    UI_SWIPE_UP,
    UI_SWIPE_DOWN,
} ui_swipe_dir_t;

static int16_t s_swipe_x0;
static int16_t s_swipe_y0;

static ui_swipe_dir_t ui_swipe_vertical(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_indev_t * indev = lv_indev_active();
    lv_point_t p;

    if(indev == NULL) return UI_SWIPE_NONE;

    if(code == LV_EVENT_PRESSED) {
        lv_indev_get_point(indev, &p);
        s_swipe_x0 = p.x;
        s_swipe_y0 = p.y;
        return UI_SWIPE_NONE;
    }

    if(code != LV_EVENT_RELEASED) return UI_SWIPE_NONE;

    lv_indev_get_point(indev, &p);
    int16_t dx = (int16_t)(p.x - s_swipe_x0);
    int16_t dy = (int16_t)(p.y - s_swipe_y0);

    if(LV_ABS(dy) < UI_SWIPE_MIN_PX) return UI_SWIPE_NONE;
    if(LV_ABS(dy) < LV_ABS(dx)) return UI_SWIPE_NONE;

    return (dy < 0) ? UI_SWIPE_UP : UI_SWIPE_DOWN;
}
#endif

///////////////////// FUNCTIONS ////////////////////
void ui_event_watch_digital( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

#ifdef APOLLO510DL_LITE
#ifdef UI_HAS_BLOOD_OXY
    ui_swipe_dir_t vswipe = ui_swipe_vertical(e);
    if(vswipe == UI_SWIPE_UP || vswipe == UI_SWIPE_DOWN) {
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
      return;
    }
#endif
#endif

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_analog, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_analog_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_analog, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_analog_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      left_Animation(ui_watch_digital_hour_group, 0);
      right_Animation(ui_watch_digital_label_min, 0);
      opa_on_Animation(ui_watch_digital_weather_group_1, 300);
      opa_on_Animation(ui_watch_digital_date_group, 500);
      opa_on_Animation(ui_watch_digital_weather_title_group_1, 400);
#ifdef APOLLO510DL_LITE
#ifndef UI_HAS_CALL
      lv_obj_add_flag(ui_watch_digital_button_top, LV_OBJ_FLAG_HIDDEN);
#endif
#ifndef UI_HAS_WEATHER
      lv_obj_add_flag(ui_watch_digital_button_down, LV_OBJ_FLAG_HIDDEN);
#endif
#endif
}
#ifdef UI_HAS_BLOOD_OXY
#ifndef APOLLO510DL_LITE
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
#endif
#endif
}

void ui_event_watch_digital_button_top_buttontop( lv_event_t * e) {
#ifdef UI_HAS_CALL
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_call, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_call_screen_init);
}
#endif
}

void ui_event_watch_digital_button_down_buttondown( lv_event_t * e) {
#ifdef UI_HAS_WEATHER
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
}
#endif
}

void ui_event_watch_analog( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

#ifdef APOLLO510DL_LITE
#ifdef UI_HAS_BLOOD_OXY
    ui_swipe_dir_t vswipe = ui_swipe_vertical(e);
    if(vswipe == UI_SWIPE_UP || vswipe == UI_SWIPE_DOWN) {
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
      return;
    }
#endif
#endif

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      min_Animation(ui_watch_analog_min, 0);
      hour_Animation(ui_watch_analog_hour, 0);
      opa_on_Animation(ui_watch_analog_weather_group_5, 300);
      opa_on_Animation(ui_watch_analog_date_group2, 500);
      opa_on_Animation(ui_watch_analog_weather_title_group_2, 400);
#ifdef APOLLO510DL_LITE
#ifndef UI_HAS_CALL
      lv_obj_add_flag(ui_watch_analog_button_top1, LV_OBJ_FLAG_HIDDEN);
#endif
#ifndef UI_HAS_WEATHER
      lv_obj_add_flag(ui_watch_analog_button_down1, LV_OBJ_FLAG_HIDDEN);
#endif
#endif
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
#ifdef UI_HAS_BLOOD_OXY
#ifndef APOLLO510DL_LITE
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
#endif
#endif
}

void ui_event_watch_analog_button_top1_buttontop( lv_event_t * e) {
#ifdef UI_HAS_CALL
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_call, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_call_screen_init);
}
#endif
}

void ui_event_watch_analog_button_down1_buttondown( lv_event_t * e) {
#ifdef UI_HAS_WEATHER
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
}
#endif
}

#ifdef UI_HAS_CALL
void ui_event_call( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_call_avatar, 0);
      opa_on_Animation(ui_call_avatar_label, 300);
      opa_on_Animation(ui_call_call_time, 400);
      opa_on_Animation(ui_call_mute, 500);
}
}

void ui_event_call_button_down2_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

void ui_event_call_volume_arc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_call_volume_percent, target, "", "%");
}
}

void ui_event_call_button_top2_buttontop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_analog, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_analog_screen_init);
}
}

#endif

#ifdef UI_HAS_WEATHER
void ui_event_weather_1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      left_Animation(ui_weather_1_label_degree, 0);
      right_Animation(ui_weather_1_sun, 100);
      right_Animation(ui_weather_1_clouds, 200);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_weather_2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_2_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_weather_2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_2_screen_init);
}
}

void ui_event_weather_1_button_down3_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

void ui_event_weather_2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_weather_1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_weather_1_screen_init);
}
}

void ui_event_weather_2_button_down4_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

#endif

void ui_event_blood_oxy( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

#ifdef APOLLO510DL_LITE
    ui_swipe_dir_t vswipe = ui_swipe_vertical(e);
    if(vswipe == UI_SWIPE_UP || vswipe == UI_SWIPE_DOWN) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
      return;
    }
#endif

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_blood_oxy_blood_presure_group, 0);
      opa_on_Animation(ui_blood_oxy_arc_spo2, 100);
      opa_on_Animation(ui_blood_oxy_pulse_group, 200);
      opa_on_Animation(ui_blood_oxy_button_round, 300);
      opa_on_Animation(ui_blood_oxy_blood_presure_group, 0);
      top_Animation(ui_blood_oxy_title_group_1, 0);
}
#ifndef APOLLO510DL_LITE
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_ecg, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_ecg_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_pressure, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_pressure_screen_init);
}
#endif
}

void ui_event_blood_oxy_button_down5_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

void ui_event_blood_oxy_button_round_buttonround( lv_event_t * e) {
#ifndef APOLLO510DL_LITE
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_measuing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_measuing_screen_init);
}
#endif
}

#ifndef APOLLO510DL_LITE
void ui_event_ecg( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_ecg_chart_group, 0);
      opa_on_Animation(ui_ecg_pulse_group1, 100);
      opa_on_Animation(ui_ecg_button_round1, 200);
      opa_on_Animation(ui_ecg_chart_ecg, 0);
      top_Animation(ui_ecg_title_group_2, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_pressure, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_pressure_screen_init);
}
}

void ui_event_ecg_button_down6_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

void ui_event_ecg_button_round1_buttonround( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_measuing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_measuing_screen_init);
}
}

void ui_event_blood_pressure( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_blood_pressure_blood_presure_group1, 0);
      opa_on_Animation(ui_blood_pressure_blood_presure_group1, 0);
      top_Animation(ui_blood_pressure_blood_presure_group2, 100);
      opa_on_Animation(ui_blood_pressure_blood_presure_group2, 100);
      opa_on_Animation(ui_blood_pressure_button_round2, 200);
      top_Animation(ui_blood_pressure_title_group_3, 0);
      top_Animation(ui_blood_pressure_pulse_group2, 100);
      opa_on_Animation(ui_blood_pressure_pulse_group2, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_ecg, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_ecg_screen_init);
}
}

void ui_event_blood_pressure_button_down7_buttondown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_watch_digital, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_watch_digital_screen_init);
}
}

void ui_event_blood_pressure_button_round2_buttonround( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_measuing, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_measuing_screen_init);
}
}

void ui_event_measuing( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      top_Animation(ui_measuing_blood_group, 0);
      opa_on_Animation(ui_measuing_blood_group, 0);
      opa_on_Animation(ui_measuing_Spinner2, 300);
      opa_on_Animation(ui_measuing_pulse_group3, 200);
      opa_on_Animation(ui_measuing_measuring, 300);
      opa_on_Animation(ui_measuing_x_button, 300);
}
}

void ui_event_measuing_x_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_blood_oxy, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_blood_oxy_screen_init);
}
}

#endif

void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      sec_Animation(ui_watch_digital_sec_dot, 0);
      sec_Animation(ui_watch_analog_sec, 0);
      dots_Animation(ui_watch_analog_dots, 0);
#ifdef UI_HAS_WEATHER
      cloud_Animation(ui_weather_1_clouds, 0);
#endif
#ifndef APOLLO510DL_LITE
      blood1_Animation(ui_measuing_blood1, 0);
      blood2_Animation(ui_measuing_blood2, 0);
      heart_Animation(ui_comp_get_child(ui_measuing_pulse_group3, UI_COMP_PULSEGROUP_HEART), 0);
#endif
}
}

///////////////////// SCREENS ////////////////////

#ifdef APOLLO510DL_LITE
static void ui_clear_scrollable(lv_obj_t * obj)
{
    lv_obj_remove_flag(obj, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);
    uint32_t i, cnt = lv_obj_get_child_count(obj);
    for(i = 0; i < cnt; i++) {
        ui_clear_scrollable(lv_obj_get_child(obj, i));
    }
}

static void ui_enable_event_bubble_children(lv_obj_t * obj)
{
    uint32_t i, cnt = lv_obj_get_child_count(obj);
    for(i = 0; i < cnt; i++) {
        lv_obj_t * child = lv_obj_get_child(obj, i);
        lv_obj_add_flag(child, LV_OBJ_FLAG_EVENT_BUBBLE);
        ui_enable_event_bubble_children(child);
    }
}
#endif

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_simple_init(dispp);
wallpaper_texture_init();
lv_disp_set_theme(dispp, theme);
ui_watch_digital_screen_init();
ui_watch_analog_screen_init();
#ifdef UI_HAS_BLOOD_OXY
ui_blood_oxy_screen_init();
#endif
#ifdef UI_HAS_WEATHER
ui_weather_1_screen_init();
ui_weather_2_screen_init();
#endif
#ifdef UI_HAS_CALL
ui_call_screen_init();
#endif
#ifdef APOLLO510DL_LITE
ui_clear_scrollable(ui_watch_digital);
ui_clear_scrollable(ui_watch_analog);
#ifdef UI_HAS_BLOOD_OXY
ui_clear_scrollable(ui_blood_oxy);
#endif
#ifdef UI_HAS_WEATHER
ui_clear_scrollable(ui_weather_1);
ui_clear_scrollable(ui_weather_2);
#endif
#ifdef UI_HAS_CALL
ui_clear_scrollable(ui_call);
#endif
ui_enable_event_bubble_children(ui_watch_digital);
ui_enable_event_bubble_children(ui_watch_analog);
#ifdef UI_HAS_BLOOD_OXY
ui_enable_event_bubble_children(ui_blood_oxy);
#endif
#ifdef UI_HAS_WEATHER
ui_enable_event_bubble_children(ui_weather_1);
ui_enable_event_bubble_children(ui_weather_2);
#endif
#ifdef UI_HAS_CALL
ui_enable_event_bubble_children(ui_call);
#endif
#endif
#ifndef APOLLO510DL_LITE
ui_ecg_screen_init();
ui_blood_pressure_screen_init();
ui_measuing_screen_init();
#endif
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_watch_digital);
}
