// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void sec_Animation( lv_obj_t *TargetObject, int delay);
void min_Animation( lv_obj_t *TargetObject, int delay);
void hour_Animation( lv_obj_t *TargetObject, int delay);
void left_Animation( lv_obj_t *TargetObject, int delay);
void right_Animation( lv_obj_t *TargetObject, int delay);
void opa_on_Animation( lv_obj_t *TargetObject, int delay);
void dots_Animation( lv_obj_t *TargetObject, int delay);
void top_Animation( lv_obj_t *TargetObject, int delay);
void cloud_Animation( lv_obj_t *TargetObject, int delay);
void blood2_Animation( lv_obj_t *TargetObject, int delay);
void blood1_Animation( lv_obj_t *TargetObject, int delay);
void heart_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_watch_digital
void ui_watch_digital_screen_init(void);
void ui_event_watch_digital( lv_event_t * e);
extern lv_obj_t *ui_watch_digital;
extern lv_obj_t *ui_watch_digital_bg_1;
extern lv_obj_t *ui_watch_digital_hour_group;
extern lv_obj_t *ui_watch_digital_label_hour_1;
extern lv_obj_t *ui_watch_digital_label_hour_2;
extern lv_obj_t *ui_watch_digital_label_min;
extern lv_obj_t *ui_watch_digital_battery_group;
extern lv_obj_t *ui_watch_digital_date_group;
extern lv_obj_t *ui_watch_digital_weather_group_1;
extern lv_obj_t *ui_watch_digital_weather_title_group_1;
extern lv_obj_t *ui_watch_digital_step_group;
extern lv_obj_t *ui_watch_digital_daily_mission_group;
void ui_event_watch_digital_button_top_buttontop( lv_event_t * e);
extern lv_obj_t *ui_watch_digital_button_top;
void ui_event_watch_digital_button_down_buttondown( lv_event_t * e);
extern lv_obj_t *ui_watch_digital_button_down;
extern lv_obj_t *ui_watch_digital_sec_dot;
extern lv_obj_t *ui_watch_digital_weather_dots_group2;
extern lv_obj_t *ui_watch_digital_dot14;
extern lv_obj_t *ui_watch_digital_dot15;
// CUSTOM VARIABLES

// SCREEN: ui_watch_analog
void ui_watch_analog_screen_init(void);
void ui_event_watch_analog( lv_event_t * e);
extern lv_obj_t *ui_watch_analog;
extern lv_obj_t *ui_watch_analog_bg_2;
extern lv_obj_t *ui_watch_analog_clock;
extern lv_obj_t *ui_watch_analog_dots;
extern lv_obj_t *ui_watch_analog_battery_group1;
extern lv_obj_t *ui_watch_analog_date_group2;
extern lv_obj_t *ui_watch_analog_day2;
extern lv_obj_t *ui_watch_analog_month2;
extern lv_obj_t *ui_watch_analog_year2;
extern lv_obj_t *ui_watch_analog_weather_title_group_2;
extern lv_obj_t *ui_watch_analog_weather_group_5;
extern lv_obj_t *ui_watch_analog_degree_7;
extern lv_obj_t *ui_watch_analog_cloud_fog_3;
extern lv_obj_t *ui_watch_analog_step_group2;
extern lv_obj_t *ui_watch_analog_daily_mission_group1;
void ui_event_watch_analog_button_top1_buttontop( lv_event_t * e);
extern lv_obj_t *ui_watch_analog_button_top1;
void ui_event_watch_analog_button_down1_buttondown( lv_event_t * e);
extern lv_obj_t *ui_watch_analog_button_down1;
extern lv_obj_t *ui_watch_analog_clock_group;
extern lv_obj_t *ui_watch_analog_sec;
extern lv_obj_t *ui_watch_analog_min;
extern lv_obj_t *ui_watch_analog_hour;
extern lv_obj_t *ui_watch_analog_dots_group;
extern lv_obj_t *ui_watch_analog_dot16;
extern lv_obj_t *ui_watch_analog_dot17;
// CUSTOM VARIABLES

// SCREEN: ui_call
void ui_call_screen_init(void);
void ui_event_call( lv_event_t * e);
extern lv_obj_t *ui_call;
extern lv_obj_t *ui_call_bg_3;
extern lv_obj_t *ui_call_avatar;
extern lv_obj_t *ui_call_avatar_label;
extern lv_obj_t *ui_call_call_time;
extern lv_obj_t *ui_call_mute;
void ui_event_call_button_down2_buttondown( lv_event_t * e);
extern lv_obj_t *ui_call_button_down2;
extern lv_obj_t *ui_call_volume_group;
extern lv_obj_t *ui_call_volume_percent;
extern lv_obj_t *ui_call_volume_image;
void ui_event_call_volume_arc( lv_event_t * e);
extern lv_obj_t *ui_call_volume_arc;
void ui_event_call_button_top2_buttontop( lv_event_t * e);
extern lv_obj_t *ui_call_button_top2;
// CUSTOM VARIABLES

// SCREEN: ui_weather_1
void ui_weather_1_screen_init(void);
void ui_event_weather_1( lv_event_t * e);
extern lv_obj_t *ui_weather_1;
extern lv_obj_t *ui_weather_1_bg_4;
extern lv_obj_t *ui_weather_1_city_gruop_1;
extern lv_obj_t *ui_weather_1_weather_title_group_3;
extern lv_obj_t *ui_weather_1_label_degree;
extern lv_obj_t *ui_weather_1_rain_group;
extern lv_obj_t *ui_weather_1_rain_icon;
extern lv_obj_t *ui_weather_1_rain_percent;
extern lv_obj_t *ui_weather_1_wind_group;
extern lv_obj_t *ui_weather_1_wind_icon;
extern lv_obj_t *ui_weather_1_wind_speed;
extern lv_obj_t *ui_weather_1_weather_dots_group;
extern lv_obj_t *ui_weather_1_dot1;
extern lv_obj_t *ui_weather_1_dot2;
extern lv_obj_t *ui_weather_1_weather_image_group;
extern lv_obj_t *ui_weather_1_sun;
extern lv_obj_t *ui_weather_1_clouds;
void ui_event_weather_1_button_down3_buttondown( lv_event_t * e);
extern lv_obj_t *ui_weather_1_button_down3;
// CUSTOM VARIABLES

// SCREEN: ui_weather_2
void ui_weather_2_screen_init(void);
void ui_event_weather_2( lv_event_t * e);
extern lv_obj_t *ui_weather_2;
extern lv_obj_t *ui_weather_2_bg5;
extern lv_obj_t *ui_weather_2_weather_dots_group1;
extern lv_obj_t *ui_weather_2_dot3;
extern lv_obj_t *ui_weather_2_dot4;
extern lv_obj_t *ui_weather_2_content;
extern lv_obj_t *ui_weather_2_city_gruop_2;
extern lv_obj_t *ui_weather_2_todady_weather_content;
extern lv_obj_t *ui_weather_2_today_weather_group;
extern lv_obj_t *ui_weather_2_today_weather_group1;
extern lv_obj_t *ui_weather_2_today_weather_group2;
extern lv_obj_t *ui_weather_2_today_weather_group3;
extern lv_obj_t *ui_weather_2_today_weather_group4;
extern lv_obj_t *ui_weather_2_today_weather_group5;
extern lv_obj_t *ui_weather_2_today_weather_group6;
extern lv_obj_t *ui_weather_2_today_weather_group7;
extern lv_obj_t *ui_weather_2_today_weather_group8;
extern lv_obj_t *ui_weather_2_days_forecast;
extern lv_obj_t *ui_weather_2_week_weather_group;
extern lv_obj_t *ui_weather_2_forecast_group;
extern lv_obj_t *ui_weather_2_forecast_group1;
extern lv_obj_t *ui_weather_2_forecast_group2;
extern lv_obj_t *ui_weather_2_forecast_group3;
extern lv_obj_t *ui_weather_2_forecast_group4;
extern lv_obj_t *ui_weather_2_forecast_group5;
extern lv_obj_t *ui_weather_2_space;
void ui_event_weather_2_button_down4_buttondown( lv_event_t * e);
extern lv_obj_t *ui_weather_2_button_down4;
// CUSTOM VARIABLES

// SCREEN: ui_blood_oxy
void ui_blood_oxy_screen_init(void);
void ui_event_blood_oxy( lv_event_t * e);
extern lv_obj_t *ui_blood_oxy;
extern lv_obj_t *ui_blood_oxy_bg6;
extern lv_obj_t *ui_blood_oxy_title_group_1;
void ui_event_blood_oxy_button_down5_buttondown( lv_event_t * e);
extern lv_obj_t *ui_blood_oxy_button_down5;
void ui_event_blood_oxy_button_round_buttonround( lv_event_t * e);
extern lv_obj_t *ui_blood_oxy_button_round;
extern lv_obj_t *ui_blood_oxy_blood_presure_group;
extern lv_obj_t *ui_blood_oxy_blood_oxygen;
extern lv_obj_t *ui_blood_oxy_percent;
extern lv_obj_t *ui_blood_oxy_pulse_group;
extern lv_obj_t *ui_blood_oxy_arc_spo2;
extern lv_obj_t *ui_blood_oxy_precent_70;
extern lv_obj_t *ui_blood_oxy_precent_100;
extern lv_obj_t *ui_blood_oxy_health_dots_group;
extern lv_obj_t *ui_blood_oxy_dot7;
extern lv_obj_t *ui_blood_oxy_dot6;
extern lv_obj_t *ui_blood_oxy_dot5;
extern lv_obj_t *ui_blood_oxy_dots_group1;
extern lv_obj_t *ui_blood_oxy_dot18;
extern lv_obj_t *ui_blood_oxy_dot19;
// CUSTOM VARIABLES

// SCREEN: ui_ecg
void ui_ecg_screen_init(void);
void ui_event_ecg( lv_event_t * e);
extern lv_obj_t *ui_ecg;
extern lv_obj_t *ui_ecg_Image1;
extern lv_obj_t *ui_ecg_bg1;
extern lv_obj_t *ui_ecg_title_group_2;
void ui_event_ecg_button_down6_buttondown( lv_event_t * e);
extern lv_obj_t *ui_ecg_button_down6;
void ui_event_ecg_button_round1_buttonround( lv_event_t * e);
extern lv_obj_t *ui_ecg_button_round1;
extern lv_obj_t *ui_ecg_pulse_group1;
extern lv_obj_t *ui_ecg_health_dots_group1;
extern lv_obj_t *ui_ecg_dot9;
extern lv_obj_t *ui_ecg_dot8;
extern lv_obj_t *ui_ecg_dot10;
extern lv_obj_t *ui_ecg_chart_group;
extern lv_obj_t *ui_ecg_chart_ecg;
extern lv_obj_t *ui_ecg_chart_ecg_Xaxis;
extern lv_obj_t *ui_ecg_chart_ecg_Yaxis1;
extern lv_obj_t *ui_ecg_chart_ecg_Yaxis2;
// CUSTOM VARIABLES

// SCREEN: ui_blood_pressure
void ui_blood_pressure_screen_init(void);
void ui_event_blood_pressure( lv_event_t * e);
extern lv_obj_t *ui_blood_pressure;
extern lv_obj_t *ui_blood_pressure_bg2;
extern lv_obj_t *ui_blood_pressure_Image3;
extern lv_obj_t *ui_blood_pressure_title_group_3;
void ui_event_blood_pressure_button_down7_buttondown( lv_event_t * e);
extern lv_obj_t *ui_blood_pressure_button_down7;
void ui_event_blood_pressure_button_round2_buttonround( lv_event_t * e);
extern lv_obj_t *ui_blood_pressure_button_round2;
extern lv_obj_t *ui_blood_pressure_blood_presure_group1;
extern lv_obj_t *ui_blood_pressure_sys_group;
extern lv_obj_t *ui_blood_pressure_sys;
extern lv_obj_t *ui_blood_pressure_mmhg1;
extern lv_obj_t *ui_blood_pressure_blood_oxygen1;
extern lv_obj_t *ui_blood_pressure_pulse_group2;
extern lv_obj_t *ui_blood_pressure_blood_presure_group2;
extern lv_obj_t *ui_blood_pressure_dia_group;
extern lv_obj_t *ui_blood_pressure_dia;
extern lv_obj_t *ui_blood_pressure_mmhg2;
extern lv_obj_t *ui_blood_pressure_blood_oxygen2;
extern lv_obj_t *ui_blood_pressure_health_dots_group2;
extern lv_obj_t *ui_blood_pressure_dot12;
extern lv_obj_t *ui_blood_pressure_dot13;
extern lv_obj_t *ui_blood_pressure_dot11;
// CUSTOM VARIABLES

// SCREEN: ui_measuing
void ui_measuing_screen_init(void);
void ui_event_measuing( lv_event_t * e);
extern lv_obj_t *ui_measuing;
extern lv_obj_t *ui_measuing_bg7;
extern lv_obj_t *ui_measuing_pulse_group3;
extern lv_obj_t *ui_measuing_measuring;
extern lv_obj_t *ui_measuing_Spinner2;
extern lv_obj_t *ui_measuing_blood_group;
extern lv_obj_t *ui_measuing_blood1;
extern lv_obj_t *ui_measuing_blood_fill;
extern lv_obj_t *ui_measuing_blood2;
void ui_event_measuing_x_button( lv_event_t * e);
extern lv_obj_t *ui_measuing_x_button;
extern lv_obj_t *ui_measuing_x;
// CUSTOM VARIABLES

// EVENTS
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bg1_png);   // assets/bg1.png
LV_IMG_DECLARE( ui_img_flash_png);   // assets/flash.png
LV_IMG_DECLARE( ui_img_weather_sun_cloud_png);   // assets/weather_sun_cloud.png
LV_IMG_DECLARE( ui_img_step_png);   // assets/step.png
LV_IMG_DECLARE( ui_img_daily_mission_png);   // assets/daily_mission.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets/call1.png
LV_IMG_DECLARE( ui_img_btn_bg_1_png);   // assets/btn_bg_1.png
LV_IMG_DECLARE( ui_img_weather_png);   // assets/weather.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets/btn_bg_3.png
LV_IMG_DECLARE( ui_img_sec_dot_png);   // assets/sec_dot.png
LV_IMG_DECLARE( ui_img_clockwise_sec_png);   // assets/clockwise_sec.png
LV_IMG_DECLARE( ui_img_clockwise_min_png);   // assets/clockwise_min.png
LV_IMG_DECLARE( ui_img_clockwise_hour_png);   // assets/clockwise_hour.png
LV_IMG_DECLARE( ui_img_bg3_png);   // assets/bg3.png
LV_IMG_DECLARE( ui_img_samatha_png);   // assets/samatha.png
LV_IMG_DECLARE( ui_img_mute_png);   // assets/mute.png
LV_IMG_DECLARE( ui_img_unmute_png);   // assets/unmute.png
LV_IMG_DECLARE( ui_img_house_png);   // assets/house.png
LV_IMG_DECLARE( ui_img_volume_png);   // assets/volume.png
LV_IMG_DECLARE( ui_img_call2_png);   // assets/call2.png
LV_IMG_DECLARE( ui_img_rain_png);   // assets/rain.png
LV_IMG_DECLARE( ui_img_wind_png);   // assets/wind.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets/sun.png
LV_IMG_DECLARE( ui_img_clouds_png);   // assets/clouds.png
LV_IMG_DECLARE( ui_img_weather_sun_png);   // assets/weather_sun.png
LV_IMG_DECLARE( ui_img_weather_cloud_png);   // assets/weather_cloud.png
LV_IMG_DECLARE( ui_img_weather_cloud_fog_png);   // assets/weather_cloud_fog.png
LV_IMG_DECLARE( ui_img_measure_png);   // assets/measure.png
LV_IMG_DECLARE( ui_img_heart_png);   // assets/heart.png
LV_IMG_DECLARE( ui_img_s8_png);   // assets/s8.png
LV_IMG_DECLARE( ui_img_s9_png);   // assets/s9.png
LV_IMG_DECLARE( ui_img_wave2_png);   // assets/wave2.png
LV_IMG_DECLARE( ui_img_wave1_png);   // assets/wave1.png
LV_IMG_DECLARE( ui_img_x_png);   // assets/x.png

// FONTS
LV_FONT_DECLARE( ui_font_H1);
LV_FONT_DECLARE( ui_font_Number_big);
LV_FONT_DECLARE( ui_font_Number_extra);
LV_FONT_DECLARE( ui_font_Subtitle);
LV_FONT_DECLARE( ui_font_Title);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
