// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Smartwatch

#include "../ui.h"

void ui_watch_analog_screen_init(void)
{
ui_watch_analog = lv_obj_create(NULL);
lv_obj_remove_flag( ui_watch_analog, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watch_analog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog, LV_OPA_COVER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_bg_2 = ui_dynamic_wallpaper_create(ui_watch_analog);

ui_watch_analog_clock = lv_label_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_clock, 2 );
lv_obj_set_y( ui_watch_analog_clock, 75 );
lv_obj_set_align( ui_watch_analog_clock, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_watch_analog_clock,"03   27");
lv_obj_set_style_text_color(ui_watch_analog_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_clock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_clock, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_dots = lv_label_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_dots, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_dots, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_dots, 2 );
lv_obj_set_y( ui_watch_analog_dots, 72 );
lv_obj_set_align( ui_watch_analog_dots, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_watch_analog_dots,":");
lv_obj_set_style_text_color(ui_watch_analog_dots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_dots, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_dots, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_battery_group1 = ui_batterygroup_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_battery_group1, 0 );
lv_obj_set_y( ui_watch_analog_battery_group1, 20 );

ui_watch_analog_date_group2 = lv_obj_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_date_group2, 100);
lv_obj_set_height( ui_watch_analog_date_group2, 82);
lv_obj_set_x( ui_watch_analog_date_group2, 105 );
lv_obj_set_y( ui_watch_analog_date_group2, 160 );
lv_obj_set_align( ui_watch_analog_date_group2, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_watch_analog_date_group2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_watch_analog_date_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_watch_analog_date_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watch_analog_date_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog_date_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_day2 = lv_label_create(ui_watch_analog_date_group2);
lv_obj_set_width( ui_watch_analog_day2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_day2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_watch_analog_day2, LV_ALIGN_CENTER );
lv_label_set_text(ui_watch_analog_day2,"MON");
lv_obj_set_style_text_color(ui_watch_analog_day2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_day2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_day2, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_month2 = lv_label_create(ui_watch_analog_date_group2);
lv_obj_set_width( ui_watch_analog_month2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_month2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_watch_analog_month2, LV_ALIGN_CENTER );
lv_label_set_text(ui_watch_analog_month2,"18 FEB");
lv_obj_set_style_text_color(ui_watch_analog_month2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_month2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_month2, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_year2 = lv_label_create(ui_watch_analog_date_group2);
lv_obj_set_width( ui_watch_analog_year2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_year2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_watch_analog_year2, LV_ALIGN_CENTER );
lv_label_set_text(ui_watch_analog_year2,"2022");
lv_obj_set_style_text_color(ui_watch_analog_year2, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_year2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_year2, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_weather_title_group_2 = ui_titlegroup_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_weather_title_group_2, 13 );
lv_obj_set_y( ui_watch_analog_weather_title_group_2, -83 );
lv_obj_set_align( ui_watch_analog_weather_title_group_2, LV_ALIGN_BOTTOM_MID );

lv_label_set_text(ui_comp_get_child(ui_watch_analog_weather_title_group_2, UI_COMP_TITLEGROUP_TITLE),"Partly Cloudy");

lv_label_set_text(ui_comp_get_child(ui_watch_analog_weather_title_group_2, UI_COMP_TITLEGROUP_SUBTITLE),"Max: 18° Min: 12°");

ui_watch_analog_weather_group_5 = lv_obj_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_weather_group_5, 82);
lv_obj_set_height( ui_watch_analog_weather_group_5, 76);
lv_obj_set_x( ui_watch_analog_weather_group_5, -90 );
lv_obj_set_y( ui_watch_analog_weather_group_5, 1 );
lv_obj_set_align( ui_watch_analog_weather_group_5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_watch_analog_weather_group_5,LV_FLEX_FLOW_COLUMN_REVERSE);
lv_obj_set_flex_align(ui_watch_analog_weather_group_5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_watch_analog_weather_group_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watch_analog_weather_group_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog_weather_group_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_watch_analog_weather_group_5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_watch_analog_weather_group_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_degree_7 = lv_label_create(ui_watch_analog_weather_group_5);
lv_obj_set_width( ui_watch_analog_degree_7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_degree_7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_degree_7, 8 );
lv_obj_set_y( ui_watch_analog_degree_7, 0 );
lv_obj_set_align( ui_watch_analog_degree_7, LV_ALIGN_CENTER );
lv_label_set_text(ui_watch_analog_degree_7,"25°");
lv_obj_set_style_text_color(ui_watch_analog_degree_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_watch_analog_degree_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_watch_analog_degree_7, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_cloud_fog_3 = lv_image_create(ui_watch_analog_weather_group_5);
lv_image_set_src(ui_watch_analog_cloud_fog_3, &ui_img_weather_sun_cloud_png);
lv_obj_set_width( ui_watch_analog_cloud_fog_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_cloud_fog_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_watch_analog_cloud_fog_3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_watch_analog_cloud_fog_3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_watch_analog_cloud_fog_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_watch_analog_step_group2 = ui_stepgroup_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_step_group2, 0 );
lv_obj_set_y( ui_watch_analog_step_group2, -40 );

ui_watch_analog_daily_mission_group1 = ui_dailymissiongroup_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_daily_mission_group1, 0 );
lv_obj_set_y( ui_watch_analog_daily_mission_group1, 0 );

ui_watch_analog_button_top1 = ui_buttontop_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_button_top1, 145 );
lv_obj_set_y( ui_watch_analog_button_top1, -105 );

ui_watch_analog_button_down1 = ui_buttondown_create(ui_watch_analog);
lv_obj_set_x( ui_watch_analog_button_down1, 146 );
lv_obj_set_y( ui_watch_analog_button_down1, 102 );

ui_watch_analog_clock_group = lv_obj_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_clock_group, 350);
lv_obj_set_height( ui_watch_analog_clock_group, 350);
lv_obj_set_align( ui_watch_analog_clock_group, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_watch_analog_clock_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watch_analog_clock_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog_clock_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_sec = lv_image_create(ui_watch_analog_clock_group);
lv_image_set_src(ui_watch_analog_sec, &ui_img_clockwise_sec_png);
lv_obj_set_width( ui_watch_analog_sec, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_sec, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_sec, 0 );
lv_obj_set_y( ui_watch_analog_sec, -67 );
lv_obj_set_align( ui_watch_analog_sec, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_watch_analog_sec, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_watch_analog_sec, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_pivot(ui_watch_analog_sec,15,155);
lv_image_set_rotation(ui_watch_analog_sec,12000);

ui_watch_analog_min = lv_image_create(ui_watch_analog_clock_group);
lv_image_set_src(ui_watch_analog_min, &ui_img_clockwise_min_png);
lv_obj_set_width( ui_watch_analog_min, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_min, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_min, 0 );
lv_obj_set_y( ui_watch_analog_min, -75 );
lv_obj_set_align( ui_watch_analog_min, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_watch_analog_min, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_watch_analog_min, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_pivot(ui_watch_analog_min,9,153);

ui_watch_analog_hour = lv_image_create(ui_watch_analog_clock_group);
lv_image_set_src(ui_watch_analog_hour, &ui_img_clockwise_hour_png);
lv_obj_set_width( ui_watch_analog_hour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_watch_analog_hour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_watch_analog_hour, 0 );
lv_obj_set_y( ui_watch_analog_hour, -45 );
lv_obj_set_align( ui_watch_analog_hour, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_watch_analog_hour, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_watch_analog_hour, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_pivot(ui_watch_analog_hour,9,93);

ui_watch_analog_dots_group = lv_obj_create(ui_watch_analog);
lv_obj_set_width( ui_watch_analog_dots_group, 20);
lv_obj_set_height( ui_watch_analog_dots_group, 50);
lv_obj_set_x( ui_watch_analog_dots_group, -10 );
lv_obj_set_y( ui_watch_analog_dots_group, 0 );
lv_obj_set_align( ui_watch_analog_dots_group, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_watch_analog_dots_group,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_watch_analog_dots_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_watch_analog_dots_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_watch_analog_dots_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog_dots_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_watch_analog_dots_group, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_watch_analog_dots_group, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_dot16 = lv_obj_create(ui_watch_analog_dots_group);
lv_obj_set_width( ui_watch_analog_dot16, 10);
lv_obj_set_height( ui_watch_analog_dot16, 10);
lv_obj_set_align( ui_watch_analog_dot16, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_watch_analog_dot16, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_watch_analog_dot16, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_watch_analog_dot17 = lv_obj_create(ui_watch_analog_dots_group);
lv_obj_set_width( ui_watch_analog_dot17, 6);
lv_obj_set_height( ui_watch_analog_dot17, 6);
lv_obj_set_align( ui_watch_analog_dot17, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_watch_analog_dot17, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_watch_analog_dot17, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_watch_analog_dot17, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_watch_analog_dot17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_watch_analog_button_top1, ui_event_watch_analog_button_top1_buttontop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_watch_analog_button_down1, ui_event_watch_analog_button_down1_buttondown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_watch_analog, ui_event_watch_analog, LV_EVENT_ALL, NULL);

}
