TARGET := lvgl_cellular_menu

DEFINES+= -DLV_AMBIQ_DISPLAY_BUFFER_RESX=464
DEFINES+= -DLV_AMBIQ_DISPLAY_BUFFER_RESY=464
DEFINES+= -DCPU_RUN_IN_HP_MODE
DEFINES+= -DGPU_RUN_IN_HP_MODE
DEFINES+= -DLV_AMBIQ_USE_DIRECT_MODE=1
DEFINES+= -DLV_AMBIQ_DRAW_BUFFER_RATIO=1

# lvgl_cellular_menu
INCLUDES+= -I../src
INCLUDES+= -I../src/gui

VPATH+=:../src

SRC += rtos.c
SRC += am_resources.c
SRC += gui_task.c
SRC += lvgl_cellular_menu.c
